[package]
name = "rust-interop"
version = "0.1.0"
authors = ["litch0 <6433436-litch0@users.noreply.gitlab.com>"]
edition = "2018"

[lib]
name="rust_interop"
crate-type = ["dylib"]


[dependencies]
libc = "0.2"
cstr = "0.2.8"